
CREATE TABLE EMPDUP (ID INT, NAME STRING,EMAIL STRING)

INSERT INTO EMPDUP(ID, NAME, EMAIL)
VALUES(100,'KHAN',lower('KHAN@GMAIL.COM')),
(2,'ZEENAT',lower('ZEENAT@GMAIL.COM')),
(3,'KHAN',lower('KHAN@GMAIL.COM')),
(4,'SAB',lower('SAB@GMAIL.COM')),
(5,'SAB',lower('SAB@GMAIL.COM'));

SELECT * FROM EMPDUP
-- DELETE DUPLICATE RECORDS
DELETE FROM EMPDUP WHERE ID NOT IN (
SELECT MIN(ID) AS ID FROM EMPDUP GROUP BY NAME, EMAIL
)