
'''
fetch second/nth highest score.
SCORE_CARD
NAME    SCORE
A	      100
B	      100
C	      99
D	      99
E	      99
F	      98
G	      97

1. output:
Name  SCORE
C       99
D       99
E       99 

2.Output
Name     Score
C,D,E      99

'''

CREATE OR REPLACE PROCEDURE SCORE_PROC(NTH INTEGER)
RETURNS TABLE( NAME VARCHAR, SCORE INTEGER)
LANGUAGE  SQL
AS
$$
DECLARE 
res RESULTSET DEFAULT(
WITH SCORE_DATA AS 
(
SELECT NAME,SCORE, DENSE_RANK() OVER(ORDER BY SCORE DESC) AS RNK
FROM SCORE_CARD
)
SELECT NAME,SCORE FROM SCORE_DATA 
WHERE RNK=:NTH 
);
BEGIN
   RETURN TABLE(res);
END;
$$
;

CALL SCORE_PROC(2)


CREATE OR REPLACE PROCEDURE SCORE_PROC(NTH INTEGER)
RETURNS TABLE( NAME VARCHAR, SCORE INTEGER)
LANGUAGE  SQL
AS
$$
DECLARE 
res RESULTSET DEFAULT(
WITH SCORE_DATA AS 
(
SELECT NAME,SCORE, DENSE_RANK() OVER(ORDER BY SCORE DESC) AS RNK
FROM SCORE_CARD
)
SELECT LISTAGG(DISTINCT  NAME,',') AS NAME,SCORE FROM SCORE_DATA 
WHERE RNK=:NTH GROUP BY SCORE
);
BEGIN
   RETURN TABLE(res);
END;
$$
;

CALL SCORE_PROC1(2)