use role accountadmin;
use database db2

CREATE OR REPLACE TABLE SOURCE_SCD2(
ID NUMBER,
NAME STRING,
EMAIL STRING,
COUNTRY STRING,
CREATED_AT DATE
)
SELECT * FROM SOURCE_SCD2;
SELECT * FROM TARGET_SCD2;
CREATE OR REPLACE TABLE TARGET_SCD2(
ID NUMBER,
NAME STRING,
EMAIL STRING,
COUNTRY STRING,
CREATED_AT DATE DEFAULT CURRENT_DATE() ,
START_DATE DATE,
END_DATE DATE,
FLAG CHAR(1)
)
--DAY-1
INSERT OVERWRITE INTO SOURCE_SCD2(ID, NAME, EMAIL,COUNTRY,CREATED_AT)
VALUES(1,'KHAN','khan101@gmail.com','INDIA','2024-01-05'),
(2,'TAUKIR','taukir101@gmail.com','CANADA','2024-01-06');

--DAY-2
INSERT OVERWRITE INTO SOURCE_SCD2(ID, NAME, EMAIL,COUNTRY,CREATED_AT)
VALUES(1,'KHAN','khan101@gmail.com','INDIA','2024-01-07'),
(2,'TAUKIR','taukir101@gmail.com','CANADA','2024-01-07');

--DAY3
INSERT OVERWRITE INTO SOURCE_SCD2(ID, NAME, EMAIL,COUNTRY,CREATED_AT)
VALUES(1,'KHAN','khan101@gmail.com','AUSTRALIA','2024-01-08'),
(2,'TAUKIR','taukir101@gmail.com','CANADA','2024-01-07');

--DAY4
INSERT OVERWRITE INTO SOURCE_SCD2(ID, NAME, EMAIL,COUNTRY,CREATED_AT)
VALUES(1,'KHAN','khan101@gmail.com','AUSTRALIA','2024-01-08'),
(2,'TAUKIR','taukir101@gmail.com','CANADA','2024-01-07'),
(3,'SAM','sam@gmail.com','CANADA','2024-01-15');

MERGE into TARGET_SCD2 AS Target
USING SOURCE_SCD2 AS Source
ON Source.id = Target.id
WHEN NOT MATCHED THEN
    INSERT(ID, NAME, EMAIL,COUNTRY,START_DATE,END_DATE,FLAG) 
    VALUES (Source.ID, Source.NAME, Source.EMAIL,source.COUNTRY,source.CREATED_AT,'9999-01-01','Y')
WHEN MATCHED 
AND  Target.FLAG = 'Y'
AND HASH(Source.ID, Source.NAME, Source.EMAIL,source.COUNTRY) <> HASH(Target.ID, Target.NAME, Target.EMAIL,Target.COUNTRY) 
THEN UPDATE  SET
    Target.FLAG = 'N',
    Target.END_DATE = CURRENT_DATE();

-- INSERT NEW UPATED VALUES
INSERT INTO TARGET_SCD2 (ID, NAME, EMAIL,COUNTRY,START_DATE,END_DATE,FLAG)
SELECT Source.ID, Source.NAME, Source.EMAIL,source.COUNTRY,
CURRENT_DATE() AS START_DATE ,'9999-01-01' AS END_DATE,'Y' AS FLAG

FROM SOURCE_SCD2 AS Source LEFT JOIN TARGET_SCD2 AS Target
ON Source.ID= Target.ID AND Target.FLAG = 'Y'
WHERE 
HASH(Source.ID, Source.NAME, Source.EMAIL,source.COUNTRY) <> HASH(Target.ID, Target.NAME, Target.EMAIL,Target.COUNTRY) 



SELECT * FROM SOURCE_SCD2
SELECT * FROM TARGET_SCD2




